name: Test SSH connection to Azure

on:
  push:
    branches:
      - main

jobs:
  ssh_test:
    runs-on: ubuntu-latest  # Используем Ubuntu runner для SSH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 20.107.247.116 >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/id_rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa imbydata@20.107.247.116 "date"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
