name: SSH Connection Workflow

on:
  push:
    branches:
      - main  # или другая ветка, по которой вы хотите запускать workflow

jobs:
  ssh_test:
    runs-on: ubuntu-latest  # или другая операционная система, если необходимо

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa  # установить права на ключ
        ssh-keyscan -H 20.107.247.116 >> ~/.ssh/known_hosts  # добавить хост в known_hosts

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # используем секрет из GitHub Secrets

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa imbydata@20.107.247.116 "powershell Get-Process"  # подключаемся по SSH
